### ISSUE TITLE
안녕하세요 멘티 조윤우입니다.

### ISSUE THREAD

**Issue by yoonucho** [ThinkAboutSoftware/HomeComingDay#22]
* 우선 멘토님 올해도 홈커밍데이 준비하시느라  고생많으셨습니다!  👍 👍 👍👍 👍👍 👍👍 👍👏👏👏👏👏👏👏👏👏

* 제가 멘토님의 답변을 잘못 이해했었고 그부분은 멘토님이 너무 미안해 하지 않으셔도 됩니다. 😉

* 온라인 모임도 꽤 재밌었습니다. 코로나시국에도 좋은 세상(?)에 살고 있음에  새삼 감사했습니다. 👍👍

* 그런데 제가  저질체력이라 그런지 장시간 캠을 켜고 대화하는건 오프라인 모임보다도 체력소모가  크더군요 ㅋ  끝나곤 바로 뻗어버렸었습니다. 😴

* 마지막으로 **멘토님, 박원정님, 백지훈님, 윤지윤님, 윤태원님, 이근주님, 장형규님, 정혜인님, 팽대원님** (순서는 멘토님 제외 , 오름차순로 나열) 구면인 분들도 오랜만에 봬서 반가웠고 뉴페이스분들은  초면이라 반가웠습니다.  내년에는 오프라인에서 뵐 수 있으면 좋겠습니다!  😍

**Comment by jongfeel** [comment]
첫 후기 감사합니다.

저도 온라인으로 했어도 재밌었는데, 그렇게 생각해 주셔서 감사합니다.

다음에는 더 많은 분들과 더 재밌는 모임이 꼭 오프라인으로 열렸으면 좋겠습니다.

**Comment by yoonucho** [comment]
글고보니 선물로 받은 마우스 인증샷을 안올렸었네요 ㅋ

![batch_photo_2021-02-20_14-19-29](https://user-images.githubusercontent.com/2981954/108584756-2b598b80-7387-11eb-96a4-ebc2a8a5fe12.jpg)
![batch_photo_2021-02-20_14-19-34](https://user-images.githubusercontent.com/2981954/108584755-2a285e80-7387-11eb-9d23-ba32201da71d.jpg)

**Comment by jongfeel** [comment]
늦었어도 인증샷을 올려 주시니 감사합니다. 그런데 박스 사진이 있는거 보니 사용 하고 계신건 아닌가 봅니다 ㅎㅎ

**Comment by yoonucho** [comment]
아니여요 사용중인데 박스는 안버렸습니다 ㅋ
