### ISSUE TITLE
안녕하세요, 박원정입니다. (단체 캡쳐샷, 상품 인증샷 추가)

### ISSUE THREAD

**Issue by WonjeongPark** [ThinkAboutSoftware/HomeComingDay#23]
안녕하세요, 박원정입니다.

멘토링 홈커밍 데이 초대 메일을 받고서야 이제 연말이구나 싶었는데,
결국 홈커밍을 온라인으로 진행하게 되니 이전과는 조금 다른 연말이라는게 더 실감나네요.

비록 실제로 만나 이야기하고, 같이 식사하며 이야기 나누는 것이 더 재미있고 즐거웠을테지만,
각각 다른 분야에서 삶을 살아가는 사람들이 멘토링이라는 공통점으로 모여 온라인으로 이야기 할 수 있다는 것도 신기하고,
작년 멘토링이 벌써 1년 전이라니 2020년이 정말 빠르게 지나간 것 같아서 아쉽다는 마음도 들더라구요.

어제 반가운 택배가 도착해서, 홈커밍데이 후기를 쓰면서 상품 인증샷도 올리고 제가 찍은 단체샷도 올려봅니다.
견우와 직녀마냥 1년에 1번(?) 볼까 말까한 사이지만 홈커밍데이에서 만났던 모든 멘티님들과, 백지훈 대표님 반가웠습니다.
내년에도 뵙길 기대할께요. ㅋㅋ(강조)

멘토링을 잠시 쉬게 되어 오랜만에 뵈었던 멘토님, 조만간 스터디나 모각코 참여해보겠습니다.
늘 스스로를 돌아보게하고 발전하는 방향으로 가게하는 좋은 영향력. 항상, 늘 감사합니다.

제가 더 잘 캡쳐한 것 같은(?) 단체샷과 상품인증샷 올려드릴께요.ㅋㅋㅋ

다들 집콕하는 건강한 연말 되시고 건강한 새해 맞이하시길 바랄께요.

단체 캡쳐 사진보다 큰 상품 인증샷 무슨일.......;;;;ㅜㅜ

![홈커밍 상품 인증샷_박원정](https://user-images.githubusercontent.com/41983574/102693302-f765cb00-425c-11eb-8bf5-abb2291c8427.jpg)
<img width="1279" alt="홈커밍 단체 인증샷 캡쳐_박원정" src="https://user-images.githubusercontent.com/41983574/102693308-fe8cd900-425c-11eb-8b86-44b38882708b.png">

**Comment by jongfeel** [comment]
원정님 후기 남겨 주셔서 감사합니다.

제가 보내드린 선물이 택배로 잘 전달 되었군요. 인증샷 까지 남겨주시고 ㅋㅋㅋ

그리고 원정님이 찍은 단체 사진이 더 잘나온 것 같습니다. 제가 미쳐 챙겨드리지 못한 윤우님의 모습도 있어서 귀한(?) 사진을 올려 주신 것 같습니다!

원정님도 매년 잊지 않고 홈커밍 데이에 참석해 주신다면 영광일 것 같고요.

제가 아무말도 한게 없는데도 항상 고마워 하시고 자신을 돌아볼 수 있는 좋은 기회를 가질 수 있게 한다고 하셔서
저도 기분이 좋습니다.

이번 기회로 스터디 모임이나 모각코도 종종 참여하셔서 그동안 github에 신경쓰지 못한 잔디 심기도 다시 해 보셨으면 좋겠습니다.

코로나가 끝나면 개인적으로도 한번 뵙고 싶네요.

다시 한번 감사합니다.

**Comment by yoonucho** [comment]
오앙! 저도 있네요!  😹

**Comment by jongfeel** [comment]
2년의 시간이 흘렀군요.

개인적인 카톡, 그리고 메일, 선물 보내주신 것 등등이 아직 기억이 납니다.

올해 home coming day는 오프라인으로 개최 예정입니다.
초대 메일을 보내 드릴 예정이니
오랜만에 한번 뵜으면 좋겠습니다.
