### ISSUE TITLE
2020 홈커밍데이 리뷰 - 정혜인

### ISSUE THREAD

**Issue by hi-hyein** [ThinkAboutSoftware/HomeComingDay#24]
2019년과는 다르게 코로나로 인하여 비대면 온라인 미팅으로 진행되었지만 많은 분들이 참여해 주셨고
2019년만큼이나 뜻깊고 의미 있는 시간이었습니다.

작년과 올해 모두 발표를 자진해서 했는데요.... 저는 사실 발표하는 것을 좋아하는 것도, 잘 하는 것도 아닌... 내향적인(안믿는 분들이 많음) mbti INFP에요..ㅋㅋㅋㅋㅋㅋㅋㅋ tmi 대방출

뭔가 나서서 하는 것은 저에게 어려운 일이에요. 하지만 그럼에도 불구하고 자진해서 발표했던 이유는 상품...이 아니라! 발표를 잘 마치고, 참여자분들과 이런 저런 공유를 했던 그 기억들이 일상으로 돌아갔을 때 어떤 원동력이 되더라구요.  홈커밍데이뿐만 아니라 멘토링, 멘토님의 활동들, 멘토님의 멘티분들의 활동들, 지금 진행하고 있는 모각코에서도 그런 원동력을 얻고 있습니다! 

그래서 저는 홈커밍데이를 진행해주신 멘토님과 그런 홈커밍데이를 완벽하게 만들어주신 참여자분들께 정말 감사한 마음이 듭니다. 🎉🎉🎉🎉🎉🎉🎉🎉

2020년 상상하지도 못한 코로나 바이러스로 인해 많이 변한 일상이 되어 힘든 해였던 것 같아요.
하지만 잘 이겨내어 곧 2021년을 앞두고 있네요! 2021년은 더 잘 이겨낼 수 있을 것이라 믿고, 다시 이전 일상으로 돌아갈 수 있을 것이라고도 믿어요!

2021년 홈커밍데이에는 멋진 곳에서 맛있는 간식을 먹으며 진행될 수 있기를 기대하겠습니다~ 한 가지 더 기대하는 게 있다면 멘토님과 대원님의 스윙댄스 정도 🤭 (장난)

2021년 건강하시고 복 많이 받으세요!!

**Comment by jongfeel** [comment]
Home coming day가 좋은 추억이 되고 일상의 원동력이 된다고 하니 기분이 좋네요.

주최는 제가 하지만 모두가 함께 만들어가는 행사이고, 혜인님도 그걸 잘 알고 계셔서 감사합니다.

스윙댄스는 대원님이 안된다고 하기 전까지는 준비해서 할 예정이고요
약속한 대로 내년에 home coming day가 오프라인으로 개최되면 두 배 더 좋은 간식과 상품으로 돌아오겠습니다.

내년 부터 다시 시작할 멘토링 미팅 부터 잘 시작하면 또 뿌듯한 2021년이 될 것 같습니다.

감사합니다.

**Comment by hi-hyein** [comment]
상품으로 받은 마우스 너무예뻐서 설정샷 남겨요ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
쌈무그린 만세! 감사합니다 잘 쓰겠습니다
![image](https://user-images.githubusercontent.com/29498125/104698965-6bf53200-5755-11eb-8cbe-35af30be3520.jpeg)

**Comment by jongfeel** [comment]
이렇게 예쁘게 배치해서 올려놓으니 좋아 보이네요. 뿌듯합니다 ㅋㅋㅋ

**Comment by jongfeel** [comment]
2022년이 됐습니다.

혜인님 소식이 궁금하군요.

Home coming day 2022가 오프라인으로 개최할 예정이고
초대 메일을 드릴 예정이니 참석해 주시면 감사하겠습니다.

**Comment by hi-hyein** [comment]
> 2022년이 됐습니다.
> 
> 혜인님 소식이 궁금하군요.
> 
> Home coming day 2022가 오프라인으로 개최할 예정이고 초대 메일을 드릴 예정이니 참석해 주시면 감사하겠습니다.

안녕하세요 멘토님!
정말 오랜만에 인사드리네요
이렇게 연락주셔서 인사드릴 틈?을 주셔서 감사합니다~~!
잊지않아주셔서 더 감사해요
시간만 된다면 너무너무 참여하고싶어요!!!!
당장 초대메일을 주세요

**Comment by hi-hyein** [comment]
12월 4일, 10일, 11일, 17일 18일 빕니다 아직까지는!
