### ISSUE TITLE
Review - Home coming day 2021

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/HomeComingDay#26]
늦었지만 혹시 모르실까봐 링크로 남겨봅니다.

https://github.com/ThinkAboutSoftware/HomeComingDay/blob/main/Reviews/Review_jongfeel.md

---

그리고 올해(2021년) home coming day는 12월 18일날 할 예정입니다.

**Comment by Joseph-Cha** [comment]
혹시 온라인으로 진행할 예정이라면 요즘 핫한 게더타운을 이용해보는 것은 어떨까요?

**Comment by jongfeel** [comment]
좋은 의견 감사합니다.

12월 3일로 방역 정책이 변경되어서 고민이 많은데
아마 올해도 온라인으로 해야 할 듯 싶습니다 ㅜㅜ

게더타운으로 온라인 모임을 하는 걸로 추진 해 보겠습니다.

**Comment by yoonucho** [comment]
WOW! 
요즘 메타버스에 관심이 가서 우리 모임도 메타버스 서비스 이용하면 좋겠다 생각하고 있었는데
역시 발빠른 멘토님이 적용해주셔서 너무 좋네요!
기대가 됩니다!
앗 동훈님 의견이었군요!  👍
