### ISSUE TITLE
2021 홈커밍데이 리뷰 - 차동훈

### ISSUE THREAD

**Issue by Joseph-Cha** [ThinkAboutSoftware/HomeComingDay#30]
올해 첫 홈커밍데이 등판(?)을 해서 멘티분들과 인사를 나누게 되었는데요,
개인적으로 발표를 해야 한다는 부담감 때문에 긴장도 많이 했지만 급하게 준비한 문제([링크](https://quizizz.com/admin/quiz/61b71f891b005c001d046be2))도 재밌게 즐겨주시고 발표도 잘 들어주셔서 오히려 제가 더 감사했던 시간이었습니다 ㅎㅎ

한 해를 돌이켜 보면 멘토님과 참 다양한 활동을 함께 했네요.
나아가 마무리 또한 잘된 것 같아 개인적으로 참 만족스러운 한 해인 것 같습니다.

좋은 시간 마련해주신 멘토님께 다시금 진심으로 감사하다는 말씀 전해드리고 싶고 또 함께 자리에 참석해주신 분들과는 내년에 꼭 면대면으로 대화 나눌 수 있기를 바랍니다🙏

그리고
제자 1호 혜인(@hi-hyein)님 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
내년에는 꼭 뵈어요 :D

**Comment by Joseph-Cha** [comment]
![KakaoTalk_20211224_163755217](https://user-images.githubusercontent.com/75019048/147330233-d199bb39-17bd-4b52-b07c-25a8c304b4df.jpg)

그리고 올해는 발표자가 2분 밖에 없어서 역대급 선물을 받을 수 있었습니다 ㅋㅋㅋ
원래는 마이크로소프트 서피스 블루투스 키보드(약 12만원 상당)가 발표자 상품이었지만 지금 쓰고 있는 키보드도 좋은 편이라서 

G Pro 마우스를 선물 받았습니다 (역시 약 12만원 상당)

선물 후기는 ..
진짜 미쳤습니다 성능은 확실해요 ㅋㅋㅋ
진심 무선 마우스 감도에 예민하신 분들은 한번 써보시길 권합니다 :D

**Comment by jongfeel** [comment]
한해동안 저랑 뜬 구름 잡는 얘기 듣느라 수고 많으셨고
발표자에게는 선물을 드린다고 했으니 부담 없이 잘 쓰셨으면 좋겠습니다.

내년에도 저와 함께 많은 활동을 했으면 하는 바램입니다.

동훈님 없으면 더 썰렁했을 home coming day 2021을 퀴즈와 함께 빛내 주셔서 감사합니다.

**Comment by jongfeel** [comment]
돌이켜 보면 올해는 회사에서 함께 했던 시간 보다
academic conference 2022 하면서 보낸 시간이 더 뜻깊었던 것 같습니다.

올해는 오프라인으로 개최할 예정이니
동훈님을 꼭 봤으면 좋겠습니다.

**Comment by Joseph-Cha** [comment]
> 돌이켜 보면 올해는 회사에서 함께 했던 시간 보다
> 
> academic conference 2022 하면서 보낸 시간이 더 뜻깊었던 것 같습니다.
> 
> 
> 
> 올해는 오프라인으로 개최할 예정이니
> 
> 동훈님을 꼭 봤으면 좋겠습니다.

벌써 1년이 흘렀네요! home coming day와 곧 시작될 academic conference 2023 모두 기대하고 있습니다 ㅎㅎ
아직 일정을 계획하고 계시겠지만 12월 17일만 일단 아니면 가능하고 살짝 귀뜸 드립니다..ㅋㅋㅋ

**Comment by jongfeel** [comment]
어헛

12월 17일날 하려고 했는데 ㅋㅋㅋㅋ
뭔가 안맞는군요

**Comment by Joseph-Cha** [comment]
앗... 그렇담 참석이 어려울 듯 싶습니다..
저 날짜가 송년회 하기 좋은 것 같아요 ㅠ
