### ISSUE TITLE
안녕하세요 멘티 조윤우입니다.  2021 홈커밍데이 리뷰?

### ISSUE THREAD

**Issue by yoonucho** [ThinkAboutSoftware/HomeComingDay#31]
올해도 코로나의 여파로 아쉽게 온라인으로 참여하게 되었습니다.
그래도 메타버스를 체험해보고 싶었는데 게더타운모임으로 참여할 수 있어서 신선했습니다!

2021 홈커밍데이에 참여하신  고아라님, 권영언님, 모영권님, 변지혜님, 소은영님, 송나리님, 심우정님, 원준호님, 이근주님, 이승연님, 임종현님, 정세영님, 차동훈님, 최예지님, 홍성현님, dim님   (오름차순 정렬 , 혹시라도 이름  빠진 분 있으시면 죄송합니다. ㅜㅜ)
모두 반가웠습니다.

그리고 멘토님 수고많으셨습니다.

내년에는 오프라인으로 꼭 만나요 😸 

찍어둔 스크릿샷 몇 장 올리고 퇴청하겠습니다!

###  홈커밍데이 현장(?)

![화면 캡처 2021-12-18 132121](https://user-images.githubusercontent.com/2981954/147377690-d177775e-fc1b-408c-a861-331b782a2350.jpg)
![화면 캡처 2021-12-18 145026](https://user-images.githubusercontent.com/2981954/147377695-7e75cd97-e0ea-4cb2-a127-ced79f5dad2a.jpg)
![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/2981954/147378239-0b399e45-a280-45c3-b287-a9d453a266af.gif)

### 차동훈님 주최 퀴즈 시작 전

![화면 캡처 2021-12-18 144436](https://user-images.githubusercontent.com/2981954/147377694-704143cc-a0f4-4a70-b6f7-84719aeedbe3.jpg)

### 멘토님 발표

![화면 캡처 2021-12-18 141043](https://user-images.githubusercontent.com/2981954/147377693-37e10912-5dff-4c9d-9887-d64f1c50fdea.jpg)

### 심우정님 발표

![화면 캡처 2021-12-18 161508](https://user-images.githubusercontent.com/2981954/147377686-3c2b636b-fee9-4b82-bdab-39180c621dc4.jpg)
![화면 캡처 2021-12-18 161918](https://user-images.githubusercontent.com/2981954/147377687-755a7836-b5a9-4c3e-84f3-98c87fa6c681.jpg)

### 차동훈님 발표

![화면 캡처 2021-12-18 152502](https://user-images.githubusercontent.com/2981954/147377698-3a731f5c-25da-45b9-bd75-873ee878e8ac.jpg)
![화면 캡처 2021-12-18 153134](https://user-images.githubusercontent.com/2981954/147377699-b228c8ef-d233-4ef4-bb89-b9151fbc75f0.jpg)

**Comment by jongfeel** [comment]
안녕하세요.

알게 모르게 스크린샷을 많이 찍어 놓으셨군요.
왠지 저 대신 사진을 찍어주신 것 같아서 감사합니다.

윤우님도 3년 개근해서 참여해 주셔서 큰 영광이라고 생각하고요.

내년에 오프라인으로 하면 정말 좋을 것 같다는 생각이 듭니다.

**Comment by jongfeel** [comment]
드디어 올해 오프라인으로 개최하려고 합니다.

초대 메일을 드릴 예정이니 참석해 주시면 감사하겠습니다.
